In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [3]:
#Creating a Tensor

Scalar = torch.tensor(7)
Scalar

tensor(7)

In [4]:
Scalar.ndim

0

In [5]:
item = Scalar.item()
item

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
Scalar.shape

torch.Size([])

In [14]:
matrix = torch.tensor([[6,7],
                       [8,9]])
matrix

tensor([[6, 7],
        [8, 9]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [18]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensor

Random tensor are used to start in neural network and  then the neural network adjust our random tensor to better match the data

In [22]:
# Create a Random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3492, 0.2118, 0.4502, 0.5958],
        [0.7856, 0.7683, 0.2768, 0.0632],
        [0.3829, 0.5092, 0.8583, 0.5696]])

In [23]:
random_tensor.ndim

2

In [26]:
## Say we're working on image data, then we create a random tensor to match the structure of our Image

random_image_tensor = torch.rand([224,224,3]) #Height, Width, colorChannel(R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
#Tensor with all zeroes
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
ones = torch.ones([3,4], dtype = int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [38]:
ones.dtype

torch.int64

In [47]:
rang = torch.arange(start = 1, end = 11, step = 1, dtype = int)
rang

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
ten_zeros = torch.zeros_like(input = rang)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
## Tensor DataType

#Imp cuz 3 errors u'll run into in Pytorch or Deep Learning are
# 1. Tensor not right Datatype
#2. Tensor not right shape
#3. Tensor not on right device

float_32_tensor = torch.tensor([3.0,5.0,7.0],
                                dtype = None, #What datatype is the tensor
                                device = None, #If we want to use GPU for this tensor
                                requires_grad = False # If we want to track the gradient for our tensor(for backpropagation i'm guessing)
                              )
float_32_tensor

tensor([3., 5., 7.])

In [61]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [62]:
##Tensor operations

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [64]:
#Multiplication is element wise
tensor * 10

tensor([10, 20, 30])

In [65]:
tensor - 10

tensor([-9, -8, -7])

In [66]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])