In [67]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [68]:
import torch
print(torch.__version__)

2.10.0+cpu


In [69]:
#Creating a Tensor

Scalar = torch.tensor(7)
Scalar

tensor(7)

In [70]:
Scalar.ndim

0

In [71]:
item = Scalar.item()
item

7

In [72]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [73]:
vector.ndim

1

In [74]:
vector.shape

torch.Size([2])

In [75]:
Scalar.shape

torch.Size([])

In [76]:
matrix = torch.tensor([[6,7],
                       [8,9]])
matrix

tensor([[6, 7],
        [8, 9]])

In [77]:
matrix.ndim

2

In [78]:
matrix.shape

torch.Size([2, 2])

In [79]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [80]:
tensor.ndim

3

In [81]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensor

Random tensor are used to start in neural network and  then the neural network adjust our random tensor to better match the data

In [82]:
# Create a Random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9623, 0.3454, 0.7096, 0.3268],
        [0.7200, 0.4686, 0.2212, 0.7277],
        [0.2712, 0.6464, 0.8242, 0.6993]])

In [83]:
random_tensor.ndim

2

In [84]:
## Say we're working on image data, then we create a random tensor to match the structure of our Image

random_image_tensor = torch.rand([224,224,3]) #Height, Width, colorChannel(R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [85]:
#Tensor with all zeroes
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [86]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [87]:
ones = torch.ones([3,4], dtype = int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [88]:
ones.dtype

torch.int64

In [89]:
rang = torch.arange(start = 1, end = 11, step = 1, dtype = int)
rang

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
ten_zeros = torch.zeros_like(input = rang)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
## Tensor DataType

#Imp cuz 3 errors u'll run into in Pytorch or Deep Learning are
# 1. Tensor not right Datatype
#2. Tensor not right shape
#3. Tensor not on right device

float_32_tensor = torch.tensor([3.0,5.0,7.0],
                                dtype = None, #What datatype is the tensor
                                device = None, #If we want to use GPU for this tensor
                                requires_grad = False # If we want to track the gradient for our tensor(for backpropagation i'm guessing)
                              )
float_32_tensor

tensor([3., 5., 7.])

In [92]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [93]:
##Tensor operations

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [94]:
#Multiplication is element wise
tensor * 10

tensor([10, 20, 30])

In [95]:
tensor - 10

tensor([-9, -8, -7])

In [96]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [97]:
tensor

tensor([1, 2, 3])

In [98]:
## Matrix Multiplication

torch.matmul(tensor,tensor)
#Here shapes doesnt match but it works because its a easy matrix

tensor(14)

In [99]:
#torch.mm == torch.matmul

tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [100]:
## We can fix this using taking a transpose

tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [101]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [102]:
##Tensor find min,max,mean,sum etc

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [103]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [104]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [105]:
torch.mean(x.type(torch.float32)),

(tensor(45.),)

In [106]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [107]:
## Finding the positional min and max

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [108]:
#Position/ index of min/max values
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [109]:
#Reshaping, Stacking, Squeezing,unsqueezing

x= torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [110]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [112]:
x_reshaped = x.reshape(1,3,3)
x_reshaped

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [113]:
#view

z = x.view(1,9)
#Chaning z changes x cuz here z is directly changing the memory of x(same pointers)

In [114]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [115]:
#stack tensors

x_stacked = torch.stack([x,x,x,x],dim= 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [116]:
x_reshaped.shape

torch.Size([1, 3, 3])

In [117]:
#Squeeze removes the single dimensions

x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [118]:
x_squeezed = x_reshaped.squeeze()

In [119]:
#unsqueeze adds a 1 dim to our tensor
x_squeezed.shape

torch.Size([3, 3])

In [120]:
x_squeezed.unsqueeze(dim = 0).shape

torch.Size([1, 3, 3])

In [121]:
#permute rearranges the dimensions of a target tensor in a specified order

ex = torch.rand([224,225,3])

ex.permute([2,0,1]).shape

torch.Size([3, 224, 225])

In [122]:
## NumPy and PyTorch,

#NumPy array to Tensor

array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [123]:
array+= 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [124]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [125]:
## Crazy, if we use += or ++, it doesnt create a new variable in the memory but for array = array+1 it does

In [126]:
tensor = torch.ones(3,4)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [127]:
##Reproducibility

random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

In [128]:
RANDOM_SEED = 67

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(67)
random_tensor_d = torch.rand(3,4)

random_tensor_c, random_tensor_d

(tensor([[0.7380, 0.3646, 0.8673, 0.5464],
         [0.5885, 0.9785, 0.8875, 0.9903],
         [0.3595, 0.3245, 0.8871, 0.9991]]),
 tensor([[0.7380, 0.3646, 0.8673, 0.5464],
         [0.5885, 0.9785, 0.8875, 0.9903],
         [0.3595, 0.3245, 0.8871, 0.9991]]))

In [129]:
## Accessing a GPU

!nvidia-smi

Sun Feb 15 19:22:20 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.44                 Driver Version: 591.44         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   66C    P0              5W /   40W |     696MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [130]:
torch.cuda.is_available()

False

In [131]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [132]:
torch.cuda.device_count()

0

In [133]:
## Putting tensors/ models on the GPU

tensor = torch.tensor([1,2,3], device = "cpu")

tensor.device

device(type='cpu')

In [134]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3])

In [135]:
#moving tensor back to the CPU, cuz numpy doesnt work on GPU

tensor_gpu.numpy()

array([1, 2, 3])

In [136]:
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu.device

'cpu'